development:
  adapter: postgresql
  database: afrinomics_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: afrinomics_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: afrinomics_production
  pool: 5
  timeout: 5000
